version: "3.9"
services:
  pairup:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: "postgres:15-bullseye"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD : "password"
      POSTGRES_DB : "pairup"